title: Page
tabs:
  main:
    label: Main
    icon: text
    columns:
      main:
        width: 1/1
        fields:
          main_content:
            label: Column 1
            type: textarea
            size: medium
            width: 1/2
          main_content_2:
            label: Column 2
            type: textarea
            size: medium
            width: 1/2
  uploads:
    label: Uploads
    icon: file
    sections:
      file_uploads:
        headline: Uploads
        type: files
