title: Site

tabs:
  main:
    label: Main
    icon: text
    columns:
      main_1:
        width: 1/2
        sections:
          pages:
            headline: Pages
            type: pages
            image: icon
            templates:
              - default
      main_2:
        width: 1/2
        sections:
          home:
            headline: Home
            type: pages
            template: home
          error:
            headline: Error
            type: pages
            template: error
          info:
            type: info
            headline: Formatting
            text: |
              For more information on formatting, visit [this Kirby guide](https://getkirby.com/docs/guide/content/text-formatting)
              or [this Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
  settings:
    label: Settings
    icon: cog
    columns:
      settings_1:
        width: 1/2
        fields:
          ga:
            label: Google Analytics Code
            type: text
      settings_2:
        width: 1/2
        fields:
          about:
            label: Meta Description
            type: text
